# https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        # 初始化时拉取模型（never、always）
        pull-model-strategy: never
        chat:
          # 想使用的模型
          additional-models:
            - llama3.2